framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                  max_retries: 5
                  delay: 1000
                  multiplier: 2
                  max_delay: 0

            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
          'App\Message\YakudzaRadarMessage': async
