monolog:
    channels: ['telegram', 'image', 'queue']
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
        telegram:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/telegram.log'
            channels: [ telegram ]
        image:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/image.log'
            channels: [ image ]
        queue:
          # log all messages (since debug is the lowest level)
          level: debug
          type: stream
          path: '%kernel.logs_dir%/queue.log'
          channels: [ queue ]