monolog:
    channels: ['telegram', 'image', 'queue']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        telegram:
            # log all messages (since debug is the lowest level)
            level: debug
            type: stream
            path: '%kernel.logs_dir%/telegram.log'
            channels: [ telegram ]
        image:
          # log all messages (since debug is the lowest level)
          level: debug
          type: stream
          path: '%kernel.logs_dir%/image.log'
          channels: [ image ]
        queue:
          # log all messages (since debug is the lowest level)
          level: debug
          type: stream
          path: '%kernel.logs_dir%/queue.log'
          channels: [ queue ]